### ISSUE TITLE
should input pictures size always be 416*416 

### ISSUE THREAD

**Issue by dawe1101** [xiaogangLi/tensorflow-Darknet53-YOLOv3#1]
Hello Sir,
   If my input pictures are 1920*1080, which part in these codes should i change to get results?

**Comment by xiaogangLi** [comment]
Thank you for your attention!

Well, if you want to change input size to 1920*1080, you should know three different feature map output sizes of feature pyramid network at lines 42, 44 and 46 in detector.py. The output sizes can be easily computed according to the network architecture. And then you should modify the code at lines 26 and 32 in parameters.py.
