### ISSUE TITLE
训练数据集问题

### ISSUE THREAD

**Issue by 15220194462** [xiaogangLi/tensorflow-Darknet53-YOLOv3#2]
请问训练的时候发生这个问题你怎么解决？
WARNING:tensorflow:From D:\tensorflow-Darknet53-YOLOv3-master\YOLOv3\code\loss.py:97: arg_max (from tensorflow.python.ops.gen_math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `argmax` instead

**Comment by xiaogangLi** [comment]
> 请问训练的时候发生这个问题你怎么解决？
> WARNING:tensorflow:From D:\tensorflow-Darknet53-YOLOv3-master\YOLOv3\code\loss.py:97: arg_max (from tensorflow.python.ops.gen_math_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use `argmax` instead

**Comment by xiaogangLi** [comment]
> 请问训练的时候发生这个问题你怎么解决？
> WARNING:tensorflow:From D:\tensorflow-Darknet53-YOLOv3-master\YOLOv3\code\loss.py:97: arg_max (from tensorflow.python.ops.gen_math_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use `argmax` instead

这是一个警告，你可以不用管。如果你要改的话，把tf.arg_max()改为tf.argmax()就可以了。
